# -*- coding: utf-8 -*-
###ListEx003

###Automatically generated by Colaboratory.

###Original file is located at
###  https://colab.research.google.com/drive/1EBv5gwdmRr7B7eXFb5n7jDLprQjD8V2I


import time

###**Exercício 003-1:** Desenvolva um programa que simule o funcionamento de uma máquina de somar.
###Entrada:
###O seu programa receberá um número inteiro não negativo N que denota a quantidade de números que seu
###programa receberá para computar o valor total da soma. Na sequência seu programa receberá N números reais.
###Saída:


n = int(input('Insira a quantidade de variaveis: '))
Na = float(0)
while n > 0:
  Na = Na + float(input())
  n = n-1
print('Total: ',round(Na,2))

###**Exercício 003-2:** Faça um temporizador de segundos (contagem regressiva) que passe a atualizar o tempo mais
##raramente. A contagem com o intervalo entre cada atualização fique dois segundos maior após cada uma delas.
##Por exemplo, se ele iniciar o temporizador com 50 segundos, então receberá atualizações dizendo que faltam 50,
##48, 44, 38, 30, 20 e 8 segundos (note que os intervalos entre as notificações foram 2, 4, 6, 8, 10 e 12 segundos).
##Desenvolva um programa que exiba em quais segundos o temporizador receberá atualizações, dado que o
##programa tenha sido inicializado com um tempo igual a N. 



Ti = int(input('Tempo inicial: '))
Rg =0
while Ti > 0:
  if Ti:
    Ti = int(Ti - Rg)
    time.sleep(Rg)
    if Ti > 0:
      print('Faltam ',Ti,' segundos')
    else:
      print('Acabou')
  Rg = Rg + 2

###**Exercício 003-3:**Crie um programa que permita verificar se um número N é fatorial ou não. N é fatorial caso
###exista um número X >= 0 tal que N = X!. 



n = int(input())
e = int(1)
b = int(1)
while n != e:
  if n != e:
      e = e*b
      b = b + 1
  if e > n:
    break
if n == e:
  print('Verdadeiro')   
else:
    print('Falso')

###**Exercício 003- 4:**Crie um programa que permita imprimir uma representação de um tabuleiro de xadrez.
###Entrada:
###O programa recebe um número inteiro, maior ou igual a 1, que indica a dimensão do tabuleiro. 



a = int(input())
c = a
b = a
while b > 0:
  while a != 0:
    print('o',end='')
    a = a - 1
    if a != 0:
      print('x',end='')
      a = a - 1
    else:
      print('')
      b = b - 1
  a = c
  if b == 0: 
    break

###**Exercício 003-5:** Ao observar a curva de velocidade de um motor, um engenheiro percebeu que sempre ocorria
###uma queda de velocidade quando medições eram feitas em intervalos de 10 ms. Após realizar alguns testes, ele
###observou que tais quedas não ocorriam necessariamente no mesmo momento. Intrigado pela falta de padrão,
###agora ele quer a sua ajuda para saber: dado um caso de teste, qual a primeira medição em que ocorreu uma
###queda de velocidade? 


N = int(input('Velocidade do motor: '))
ant = int(0)
b = 0
c = 0

for i in range(N):
  a = int(input('RPM: '))
  if (c == 0 and a < ant):
    b = (i + 1)
    c = 1
  elif (c == 0 and i + 1 == N):
    b = 0
  else:
    ant = a

print(b)