# -*- coding: utf-8 -*-
###ListEx001

###Automatically generated by Colaboratory.

###Original file is located at
###    https://colab.research.google.com/drive/1uHfwwJF-4EAaeqS3ddnHIlxoAXMUFy_F
###

import math

###Exercício 001-1: A fórmula para calcular a área de uma circunferência é: **área = pi . raio²**. Crie um programa para ler o valor do raio e efetuar o cálculo da área. Entrada: A entrada contém um número real, positivo, representando o raio. Saída: **Seu programa deve imprimir na tela a área do círculo com 4 casas após o ponto decimal.**"""

print('Valor do raio:') 
raio = int(input())
area = 3.1415*raio**2
print('a area é:', round(area,4))

###"""**Exercício 001-2:** Faça um programa que leia os comprimentos dos 3 lados a, b, c de um paralelepípedo. Então calcule o seu volume e sua diagonal principal, dados pelas seguintes expressões, respectivamente: 

###V = a . b . c

###d = sqrt ( a2 + b2 +c2 ), sendo sqrt a função raiz quadrada da biblioteca math

###atribuindo os resultados às variáveis **V** e **d**. A seguir, apresente as variáveis com as mensagens correspondentes, conforme exemplos abaixo. A saída deve imprimir **duas** casas decimais.


2a = float(input('Indica o valor de a '))
b = float(input('Indica o valor de b '))
c = float(input('Indica o valor de c '))
V = a * b * c
d = math.sqrt (a**2 + b**2 + c**2)
print('O Volume é ', round(V,2))
print('A diagonal principal é ', round(d,2))

###"""**Exercício 001-3:** A conversão de graus Fahrenheit para Celsius é dada pela expressão:

###**C . 1.8 = F - 32**
###e a conversão de Kelvin para graus Celsius é dada por
###**C = k - 273.15**

###Faça um programa que recebe como entrada a temperatura em graus Celsius e realize duas conversões: uma para Fahrenheit e outra para Kelvin.


C = float(input('Insira a temperatura em Celsius '))
F = C * 1.8 + 32
k = C + 273.15
print('Temperatura em Fahrenheit: ', round(F,1),'°F')
print('Temperatura em Kelvin ', round(k,1),"K")

###**Exercício 001-4:** Leia dois números inteiros a, b, e dois números em ponto flutuante x, y. Então calcule a expressão:

###a + bx – sqrt(b) + ( (a+b) / (x-y) )

###atribuindo o resultado à variável **expressao**. A seguir, mostre a variável **expressao** com a mensagem correspondente, conforme exemplos abaixo. A saída deve imprimir duas casas decimais.



a = int(input('Indique o valor de a '))
b = int(input('Indique o valor de b '))
x = float(input('Indique o valor de x '))
y = float(input('Indique o valor de y '))
expressao = a + b * x - math.sqrt(b) + ((a+b)/(x-y))
print('O resultado da expressão é ', round(expressao,2))

###**Exercício 001-5:** Faça um programa que leia o nome de um vendedor, o seu salário fixo e o total de vendas efetuadas por ele no mês (em dinheiro). Sabendo que este vendedor ganha 5% de comissão sobre suas vendas efetuadas, informar o total a receber no final do mês, com duas casas decimais."""

nome = input('Insira o nome: ')
sF = float(input('Insira o Salario fixo: R$'))
tV = float(input('Insira a venda do mês: R$'))
C = (tV/100)*5
sT = C + sF
print('O total a receber por', nome, "é: R$", round(sT,2))

###**Exercício 001-6:** Faça um programa que leia três números inteiros e apresente o maior dos três valores. ***Nesta questão está proibido usar if (isto é, não deve se usar nenhuma estrutura condicional)*** ou a função max, mas vai precisar usar a função abs(z) que retorna com o valor do módulo, sem sinal do parâmetro. **Dica**: A seguinte fórmula permite calcular o maior valor dados os números x e y:

###Max(x,y) = (x+y)/2 + abs(y-x)/2



a = int(input('Primeiro Numero: '))
b = int(input('Segundo Numero: '))
c = int(input('Terceiro Numero: '))
d = int((a+b)/2 + abs(b-a)/2)
e = int((d+c)/2 + abs(c-d)/2)
print('O Numero mais alto entre os inseridos foi:', e)

###**Exercício 001-7:** Faça um programa que leia um valor inteiro representando um valor em reais e calcule o menor número de cédulas possíveis no qual o valor pode ser decomposto. As cédulas consideradas são as de RS200.00, RS100.00, RS50.00, RS20.00, RS10.00, RS5.00, RS2.00 e RS1.00. Seu programa deve imprimir a quantidade de cada cédula. Dica: divisão inteira usa // e resto da divisão usa %

###Assim valor total RS 1317,00 quantas notas de RS 200,00

###qtdNotas200 = valorTotal // 200

###resulta 6 notas de 200 e agora o resto seria

###restoValor = valorTotal % 200

###resulta 117


Vt = float(input('Insira o valor: R$'))
qtdA = int(Vt // 200)
qtdB = int(Vt % 200)
qtdC = int(qtdB // 100)
qtdD = int(qtdB % 100)
qtdE = int(qtdD // 50)
qtdF = int(qtdD % 50)
qtdG= int(qtdF // 20)
qtdH= int(qtdF % 20)
qtdI= int(qtdH // 10)
qtdJ= int(qtdH % 10)
qtdK= int(qtdJ // 5)
qtdL= int(qtdJ % 5)
qtdM= int(qtdL // 2)
qtdN= int(qtdL % 2)
qtdO= int(qtdN // 1)
print('No total serão usadas', qtdA, ' notas de R$200. ', qtdC, 'notas de R$100. ', qtdE, 'notas de R$50. ', qtdG, 'notas de R$20. ', qtdI, 'notas de R$10. ', qtdK, 'notas de R$5. ', qtdM, 'notas de R$2 e ', qtdO, 'moedas de R$1.'  )